### ISSUE TITLE
Support for Show Whitespace plugin

### ISSUE THREAD

**Issue by onetrev** [JosephGF/bracketstheme-obsidian2#1]
Really love this theme for Brackets... just wondering if there was any chance you could add improved support for https://github.com/DennisKehrig/brackets-show-whitespace ?

Right now the spaces (dots) and tabs (dashes) are heavy / too bright I think. 

No worries either way. Cheers!

**Comment by JosephGF** [comment]
Hello, I add support form brackets-show-whitespace extension, but i have problems to upgrade the theme, you can refresh it if replace theme.css for the gitub css in \Users{user}\AppData\Roaming\Brackets\extensions\user\josephgf.obsidian2 folder

**Comment by JosephGF** [comment]
Obsidian 2.0 theme has been updated, tranks!
